import { Problem } from "@/types/problem";

export const problems: Problem[] = [
  {
    id: 1,
    title: "Two Sum",
    platform: "LeetCode",
    difficulty: "Easy",
    topic: "Array",
    solved: true,
    favorite: true,
    revisionDate: "Tomorrow",
    revisionCount: 0,
    maxRevisions: 0,
  },
  {
    id: 2,
    title: "Longest Substring Without Repeating Characters",
    platform: "LeetCode",
    difficulty: "Medium",
    topic: "Sliding Window",
    solved: true,
    favorite: false,
    revisionDate: "3 Days",
    revisionCount: 0,
    maxRevisions: 3,
  },
  {
    id: 3,
    title: "Word Ladder",
    platform: "LeetCode",
    difficulty: "Hard",
    topic: "Graph",
    solved: false,
    favorite: false,
    revisionDate: "Not Scheduled",
    revisionCount: 0,
    maxRevisions: 5,
  },
];