"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";

export default function AuthForm({ mode }: { mode: "login" | "signup" }) {
  const router = useRouter(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setError(""); setLoading(true); try { const res = await fetch(`/api/auth/${mode === "signup" ? "signup" : "login"}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(mode === "signup" ? { name, email, password } : { email, password }) }); const data = await res.json(); if (!res.ok) throw new Error(data.message || "Authentication failed"); router.push("/dashboard"); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Authentication failed"); } finally { setLoading(false); } }
  return <div className="w-full max-w-md rounded-2xl border bg-card p-6 shadow-sm"><h1 className="text-2xl font-semibold">{mode === "login" ? "Welcome back" : "Create your IntelliDSA account"}</h1><p className="mt-1 text-sm text-muted-foreground">{mode === "login" ? "Continue your DSA progress." : "Track problems and get personalized AI guidance."}</p><div className="mt-6 grid grid-cols-2 gap-2"><a className="rounded-lg border px-3 py-2 text-center text-sm hover:bg-muted" href="/api/auth/oauth/google">Continue with Google</a><a className="rounded-lg border px-3 py-2 text-center text-sm hover:bg-muted" href="/api/auth/oauth/github">GitHub</a></div><div className="my-5 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border" />OR<span className="h-px flex-1 bg-border" /></div><form onSubmit={submit} className="space-y-4">{mode === "signup" && <input value={name} onChange={(e) => setName(e.target.value)} minLength={2} maxLength={80} placeholder="Name" className="w-full rounded-lg border bg-background px-3 py-2.5" /> }<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" className="w-full rounded-lg border bg-background px-3 py-2.5" /><input required minLength={8} maxLength={128} type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password (8+ characters)" className="w-full rounded-lg border bg-background px-3 py-2.5" />{error && <p className="text-sm text-destructive">{error}</p>}<button disabled={loading} className="w-full rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground disabled:opacity-50">{loading ? "Please wait..." : mode === "login" ? "Sign in" : "Create account"}</button></form><p className="mt-5 text-center text-sm text-muted-foreground">{mode === "login" ? <>New here? <Link className="text-primary hover:underline" href="/signup">Create an account</Link></> : <>Already have an account? <Link className="text-primary hover:underline" href="/login">Sign in</Link></>}</p></div>;
}
